### ISSUE TITLE
Check if there are undefined strings 

### ISSUE THREAD

**Issue by Nuisigor** [Nuisigor/jabref#2]
Add a quality check to verify if there are undefined strings for an entry.

Original: https://github.com/magsilva/jabref/issues/36

**Comment by getuliobr** [comment]
public Optional<ConstantsItemModel> labelAlreadyExists(String label) {
        return stringsListProperty.stream()
                                  .filter(item -> item.labelProperty().getValue().equals(label))
                                  .findFirst();
    }
